### ISSUE TITLE
possible bug when when using capture or quietly prefix

### ISSUE THREAD

**Issue by remlapmot** [gvegayon/parallel#33]
Dear George,
Thanks indeed for this brilliant suite which really does speed up my work. 
I am coding to get some bootstrapped standard errors for an estimator and I find that when I prefix my "parallel bs" command with either "capture" or "quietly" it fails but if I just run it "noisily" then it completes without error.
I have observed this error on Stata 14 on Windows and Unix.
I attach an example do-file and it's log-file with the errors (note I have had to give both files an extra .txt extension so GitHub allows me to upload them).

Best wishes
  Tom Palmer

[parallel_example.log.txt](https://github.com/gvegayon/parallel/files/235156/parallel_example.log.txt)
[parallel_example.do.txt](https://github.com/gvegayon/parallel/files/235155/parallel_example.do.txt)

**Comment by gvegayon** [comment]
Tom,

The issue here is that, as far as I know, you can't export a program, in your case -logistictsri-, without printing it on screen (see lines here https://github.com/gvegayon/parallel/blob/master/ado/parallel_export_programs.mata#L29-L31). I haven't tried running parallel with other commands that don't require passing a program.

Best,

**Comment by bquistorff** [comment]
I've added a check & error message when using `programs()` but `c(noisily)==0` in 24c4f94.

**Comment by gvegayon** [comment]
Great, thanks!

George G. Vega Yon (from mobile)
+1 626 381 8171
http://www.its.caltech.edu/~gvegayon
