### ISSUE TITLE
possible use of runmlwin_qshell instead of winexec on Windows

### ISSUE THREAD

**Issue by remlapmot** [gvegayon/parallel#34]
Dear George

I wondered if you're aware of the runmlwin_qshell program which comes with another user-written command -runmlwin- (which is on SSC for running the software MLwiN from Stata)? runmlwin_qshell is their own version of Stata's shell command but prevents the pop-up DOS prompt.

Calling Stata with it (from within Stata on Windows) is as follows:
  ssc install runmlwin
  runmlwin_qshell "C:\Program Files (x86)\Stata14\StataSE-64.exe" /e do test.do
 
The author of runmlwin Chris Charlton at the University of Bristol is very helpful and I'm sure would help if you have any questions.

Best wishes 
  Tom

**Comment by gvegayon** [comment]
Tom,

Sounds interesting, I took a look at http://fmwww.bc.edu/repec/bocode/r/runmlwin_qshell.ado and indeed they are using their own plugin. I'm not very familiar with Stata plugins, so I don't know how this will work in different OSs. You are invited to propose an upgrade (or maybe leave it as optional) to parallel, for now it will be labeled as enhancement.

Thanks

**Comment by bquistorff** [comment]
The `runmlwin_qshell` plugin is only for Windows. That's fine since I think that's the only place where `parallel` causes annoying popups (the other OSes have command-line versions of Stata). I've installed `runmlwin` and then we can just substitute out `winexec` with `runmlwin_qshell` and it appears to work fine. No popups, though the background Stata processes will still briefly steal the window focus. But it's much nicer. I'll ask about re-using their code.

**Comment by bquistorff** [comment]
For the record, [here](http://superuser.com/questions/233348/how-do-i-create-a-windows-batch-file-that-does-not-show-the-command-prompt-when) appear to be some other possible solutions.

**Comment by bquistorff** [comment]
I've been playing around with this solution and I think it is great for Windows. It has the following benefits:
 - By launching the process using real system calls from the plugin we avoid having a shell window pop-up (very annoying). We can have Stata processes launched minimized, but they still "steal" the focus for a bit (mildly annoying). This can be overcome by launching them hidden (not just minimized). 
 - In batch mode we can launch using the same system as for interactive sessions. We can get rid of the "gateway" kludge (which can be tricky to get right & maintain).
 - We can easily keep track of the child process IDs (a prerequisite to #38).

I'd like to mainline this feature. Any objection? I'll look at first figuring out how to put MS Visual Studio projects in the repo. I can build both Windows 32- and 64-bit plugins.

**Comment by remlapmot** [comment]
Thanks indeed for looking into this. 

This sounds great - especially if you've found a way to stop the parallel processes on Windows stealing the focus, so the computer remains usable to do something else whilst the parallel tasks are running.

Best wishes
  Tom

**Comment by gvegayon** [comment]
Go for it. create a new branch and one tested merge it!

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by bquistorff** [comment]
OK, you can give the new Windows plugin framework a try on the `winproc` branch. 

```
ado uninstall parallel
net install parallel, from(https://raw.github.com/gvegayon/parallel/winproc/)
mata: mata mlib index
```

It's very smooth (no pop-ups or stolen focus and faster hand-offs)! Let me know how it works.

I actually implemented a suite of simple programs/plugins to allow Stata to deal with processes (maybe this will eventually be split off)
 - `procexec` starts processes. If can start them at higher priority and hide their windows (both turned on by default in `parallel`) and returns the process ID.
 - `prockill` kills a process by its PID. `parallel` now uses this when someone `break`s.
 - `procwait` checks if a PID is finished. Once `parallel` sees the `finito` file made by a child process it waits until the child process finishes before dealing the child's files (we used to manually put in `sleep`s to do deal with the fact that the child might not have exited by that point).
 - `procenv` gets and sets environment variables. `parallel` uses this to change its `STATATMP` environment variable (it's `tmpdir` doesn't change, this is set at startup) so that created processes have the appropriate `tmpdir` (child processes inherit environment variables).

The global `USE_PROCEXEC` controls usage. If `0` then it does the old `bat`-file method, if `1` it uses `procexec` but only minimizes the child windows, and if `2` it fully hides the child windows (the only way to keep focus from being stolen).

Since we now have platform-specific binaries, if you want to test what is currently in the repo (on Windows) you can't just set `S_ADO` to `<parallel>/ado;...`, you have to set it to `<parallel>/ado;<parallel/ado/<platformname>;...` where platform name is the name used in the package file (`WIN` for 32-bit and `WIN64A` for the 64-bit Windows). There are some helper utilities in `tests/` (`platformname.ado`,`export_platformname.do`) and the `makefile` and `test_all.do` use them appropriately. (Alternatively, you can just install from the repo and test that.)

I've committed the plugin code so that it can be built by anyone on MS Visual Studio 2013.

Side note: When using `procexe` I no longer set the working directory in `parallel_run`, which I don't think will cause problems with #12 (the `pushd`/`popd`), but we should check.

**Comment by remlapmot** [comment]
I ran a little example and it worked really well (no pop ups or stolen focus).

The only thing I spot is that the cluster log files were deleted after the job completed, and so -parallel printlog- had nothing to show.

Also the helpfile mentioned -parallel seelog- but I got a different error for that. Output below.

Best wishes
  Tom

. sysuse auto, clear

. parallel setclusters 4

. parallel bs, seeds(12345 56789 101112 13141) reps(500): reg price c.weig##c.weigh foreign rep
--------------------------------------------------------------------------------
Parallel Computing with Stata (by GVY)
Clusters   : 4
pll_id     : ls4uainwf7
Running at : C:\Users\palmertm\Documents\all\stata\parallel\examples
Randtype   : datetime
Waiting for the clusters to finish...
cluster 0003 has exited without error...
cluster 0004 has exited without error...
cluster 0002 has exited without error...
cluster 0001 has exited without error...
--------------------------------------------------------------------------------
Enter -parallel printlog #- to checkout logfiles.
--------------------------------------------------------------------------------

parallel bootstrapping                          Number of obs     =         69
                                                Replications      =        500

      command:  regress price c.weig##c.weigh foreign rep

-----------------------------------------------------------------------------------
                  |   Observed   Bootstrap                         Normal-based
                  |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
------------------+----------------------------------------------------------------
           weight |  -4.317581   3.200052    -1.35   0.177    -10.58957    1.954407
                  |
c.weight#c.weight |   .0012192   .0005083     2.40   0.016     .0002229    .0022155
                  |
          foreign |   3155.969   885.1275     3.57   0.000     1421.151    4890.787
            rep78 |  -30.11387   324.6291    -0.09   0.926    -666.3752    606.1475
            _cons |   6415.187   5317.318     1.21   0.228    -4006.565    16836.94
-----------------------------------------------------------------------------------

. parallel printlog 1, e(ls4uainwf7)
No logfile for instance -0001- of parallel process -ls4uainwf7- found

. parallel seelog 1, e(ls4uainwf7)
-seelog- invalid parallel subcommand (help parallel)
r(198);

**Comment by bquistorff** [comment]
Thanks for checking this! I'll merge this branch into `master`. 

The errors are separate issues, which I'll fix right now.
 - We recently had the code clean up more of the generated files when there was no error (unless one specifies `keep` or `keeplast`) so they didn't accumulate on the system. In the case where we don't keep the log we should update the display.
 - The other log command is now named `printlog`

**Comment by gvegayon** [comment]
> Thanks for checking this! I'll merge this branch into `master`.

Sounds good. Once merged I'll tested on my computers and, if you think is OK, build it so we can send it to SSC

> * The other log command is now named printlog
Thanks

**Comment by bquistorff** [comment]
OK, it's mainlined. George, would you check? Things still to do:
 - Should we keep around bat-file solution on Windows (w/ the Cygwin "hack" to make it work in batch-mode)?
 - How should the user set the execution options for Windows (minimized vs "fully hidden" vs (if we want) bat-file method)? Currently using the global `USE_PROCEXEC`.
 - Document this (depends on above).

Before posting to SSC could we do a simple solution to #36 (since that'll be a non-compatible change also)? You're much better at formatting output so I thought you'd do this better than me. I was thinking you could edit `parallel_do` to return the first non-zero error code from children.

**Comment by bquistorff** [comment]
A note about fixing DLL load errors on Windows (just for reference):
I had some DLL load failures due to corrupt files. Then loads would fail but work if the plugin files were renamed. Sometimes moving them to a new place (`ado/WIN64A/p`) allowed them to work and then they would work in the original location. Sometimes I rebuilt them (changing code size) and this seemed to work. See possibly related issue [here ](http://stackoverflow.com/questions/4483429/loading-assembly-at-runtime-fails-when-i-copy-the-dll-after-program-startup). Maybe some interaction with Stata and Windows trying to prevent DLL-hell?

**Comment by gvegayon** [comment]
> * Should we keep around bat-file solution on Windows (w/ the Cygwin "hack" to make it work in batch-mode)?

I think that this might be useful for more advance users (like yourself!), so if it doesn't hurt I think it is a good idea to keep it (but leave the new behavior as default).

> * How should the user set the execution options for Windows (minimized vs "fully hidden" vs (if we want) bat-file method)? Currently using the global USE_PROCEXEC.

I'm not completely sure about what are you asking here. But, if I'm getting it right, I think the easiest way of doing this is using ` OPtion(passthru)`. (Makes sense?)

> Maybe some interaction with Stata and Windows trying to prevent DLL-hell?

I have no idea about this, perhaps writing stata fellas might work?

**Comment by bquistorff** [comment]
OK, I've kept around the old Windows solution and allowed an option in `parallel setclusters` to set the windows spawn method. See b7fc70c.
