### ISSUE TITLE
Parallel error (608)

### ISSUE THREAD

**Issue by Bruno1206** [gvegayon/parallel#59]
# Preliminaries
Before submitting an issue, please check (with `x` in brackets) that you:
- [x ] Are using the newest release (see [here](https://github.com/gvegayon/parallel/releases) for latest release version number).
- [ x] Have checked that the examples in the help work.
- [ x] Have read the help ([HTML version](https://rawgit.com/gvegayon/parallel/master/ado/parallel.html)) and the [gallery](https://github.com/gvegayon/parallel/wiki/Gallery) of examples.
- [x] Have checked that there is not already an existing issues for what you are reporting.

# Expected behavior and actual behavior
I am trying to run the following code:
```
clear all 
cd "C:\Users\asistente.economia3\Desktop\Empleo"
parallel setclusters 4 
parallel do C:\Users\asistente.economia3\Desktop\Empleo\empgeneratorP.do
```
However, it stops midway after saving a database owning to the fact that:

> file xxxxx cannot be modified or erased; likely cause is read-only directory or file r(608).

After a "save XXXXX, replace" command.
I am running parallel v.1.19.0 on  Stata 14 on a windows 10 computer with 4 cores, so the number of clusters should not be a problem.

**Comment by bquistorff** [comment]
What is the full file path of the file it is trying to save? Is it in the `Empleo` directory or the temp directory (see ``di `c(tempdir)'``)?

**Comment by Bruno1206** [comment]
Thanks for your reply. It is in the "Empleo" directory.

**Comment by bquistorff** [comment]
Yes, at the moment the current directory needs to be writable. I'll make sure to specify this in the docs. To work around this, you could try (a) to make the folder writable if you have sufficient permissions (can find these instructions online), which you should be able to do if this is your user folder, or (b) modify your project so that you can run it from a writable folder. If this is a common enough situation we could add an `outputdir()` option to `setclusters`, but my sense is this is very uncommon (@gvegayon, feel free to weigh in).

**Comment by Bruno1206** [comment]
The issue, I believe, revolves around the fact that it is not possible to
change a directory's status from "read-only" in Windows 10 so making the
folder writable in that way is not possible.
Thank you so much for your time
Bruno Jimenez

2017-08-28 11:26 GMT-05:00 Brian Quistorff <notifications@github.com>:

**Comment by gvegayon** [comment]
Yeah, there's not much we can do to fix this, since it is not an issue on our side. At most, as Brain suggests, we can put this explicitly in our documentation. Try using a different directory, that should work.

@bquistorff, I think this may be a good thing to include in a FAQ section at the end of the documentation (which I just started).

That said, I think this issue should be closed since it is not a problem in our end.

HTH
